theme = "hugorha"
themesdir = "../.."
baseurl = "http://localhost:1313/"
title = "Hugorha Example Site"
PygmentsCodeFences = true

[params]
    [params.header]
    links = [ [ "itk", "http://www.itk.fr" ], [ "ForkMe ImFamous", "http://gitlab.com/itk.fr" ] ]

    [params.footer]
    copyrightHTML = "Copyright &#xA9; 2013 John Doe. All Rights Reserved."