theme = "hugorha"
themesdir = "../.."
baseurl = "http://localhost:1313/"
publishDir = "../docs"
title = "Hugorha"
PygmentsCodeFences = true
relativeURLs = true
enableGitInfo = true

[outputs]
    home = [ "HTML", "RSS", "JSON" ]
    page = [ "HTML" ]

[[menu.main]]
    name = "Showcase"
    weight = 3
    pre = '<i class="fa fa-desktop" aria-hidden="true"></i>'
[[menu.main]]
    name = "Lorhammer"
    parent = "Showcase"
    weight = 1
    url = "http://lorhammer.itk.fr/"
[[menu.main]]
    name = "ContinuousEvolution"
    parent = "Showcase"
    weight = 2
    url = "https://continuousevolution.gitlab.io/continuous-evolution/"

[params]
homePageTitle = "Index"
logoFileName = "images/headerLogo.png"
favicons = [
    '<link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-icon-57x57.png">',
    '<link rel="apple-touch-icon" sizes="60x60" href="/images/favicon/apple-icon-60x60.png">',
    '<link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-icon-72x72.png">',
    '<link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/apple-icon-76x76.png">',
    '<link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/apple-icon-114x114.png">',
    '<link rel="apple-touch-icon" sizes="120x120" href="/images/favicon/apple-icon-120x120.png">',
    '<link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-icon-144x144.png">',
    '<link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-icon-152x152.png">',
    '<link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-icon-180x180.png">',
    '<link rel="icon" type="image/png" sizes="192x192"  href="/images/favicon/android-icon-192x192.png">',
    '<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">',
    '<link rel="icon" type="image/png" sizes="96x96" href="/images/favicon/favicon-96x96.png">',
    '<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">',
    '<link rel="manifest" href="/images/favicon/manifest.json">',
    '<meta name="msapplication-TileColor" content="#ffffff">',
    '<meta name="msapplication-TileImage" content="/images/favicon/ms-icon-144x144.png">',
    '<meta name="theme-color" content="#ffffff">'
]

    [params.header]
    links = [
		'<a href="http://www.itk.fr" target="blank" class="btn"><i class="fa fa-leaf" aria-hidden="true"></i> itk</a>',
		'<a href="https://github.com/itkSource/hugorha" target="blank" class="btn"><i class="fa fa-code-fork" aria-hidden="true"></i> Fork Me</a>'
    ]

    [params.footer]
    copyrightHTML = "Copyright &#xA9; 2017 Itk. All Rights Reserved."

    [params.css]
    specialFontName = "font/minspsw"

    mainColor = "#468ef4"
    gradient_1 = "#468ef4"
    gradient_2 = "#266ed4"
    textColor = "#222"

    bgColor = "#fff"
    textColorOnMainColor = "#fff"

    alertColor = "red"
    siteNameBorder = false